In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ahsanaseer/top-rated-tmdb-movies-10k")

print("Path to dataset files:", path)

Path to dataset files: /Users/sophie/.cache/kagglehub/datasets/ahsanaseer/top-rated-tmdb-movies-10k/versions/1

In [2]:
import pandas as pd

movies = pd.read_csv(f"{path}/top10K-TMDB-movies.csv")

In [3]:
movies

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221

In [4]:
import seaborn as sns
import matplotlib.pyplot as plt

In [17]:
#### DATA CLEANUP - remove the movies with no genre or overview
movies[movies["overview"].isna()]

Empty DataFrame
Columns: [id, title, genre, original_language, overview, popularity, release_date, vote_average, vote_count]
Index: []

In [10]:
movies = movies.dropna(subset=["overview", "genre"])

In [11]:
movies[movies["overview"].isna()]

Empty DataFrame
Columns: [id, title, genre, original_language, overview, popularity, release_date, vote_average, vote_count]
Index: []

In [12]:
movies[movies["genre"].isna()]

Empty DataFrame
Columns: [id, title, genre, original_language, overview, popularity, release_date, vote_average, vote_count]
Index: []

In [13]:
movies

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221

In [14]:
# check duplicate movie titles
movies[movies["title"].duplicated(keep=False)].sort_values("title")

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
10,389,12 Angry Men,Drama,en,The defense and the prosecution have rested an...,31.946,1957-04-10,8.5,6533
797,12219,12 Angry Men,"Crime,Drama,TV Movie",en,During the trial of a man accused of his fathe...,8.953,1997-08-17,7.7,220
2441,14168,3:10 to Yuma,"Western,Drama,Thriller",en,"Dan Evans, a small time farmer, is hired to es...",6.606,1957-08-07,7.2,258
2491,5176,3:10 to Yuma,Western,en,"In Arizona in the late 1800s, infamous outlaw ...",21.617,2007-09-06,7.2,2885
3846,12244,9,"Action,Adventure,Animation,Science Fiction,Thr...",en,"When 9 first comes to life, he finds himself i...",53.232,2009-08-19,6.9,2952
...,...,...,...,...,...,...,...,...,...
2150,15359,Wonder Woman,"Action,Adventure,Animation,Fantasy,Science Fic...",en,"On the mystical island of Themyscira, a proud ...",18.669,2009-03-03,7.3,455
7654,630586,Wrong Turn,"Horror,Thriller",en,Jen and a group of friends set out to hike the...,124.151,2021-01-26,6.0,757
6359,9902,Wrong Turn,"Horror,Thriller",en,Chris crashes into a carload of other young pe...,74.628,2003-05-30,6.3,2064
1668,14433,Zulu,"Action,Drama,History,War",en,"In 1879, during the Anglo-Zulu War, man-of-the...",9.673,1964-01-22,7.4,395
4549,185567,Zulu,"Crime,Drama,Thriller",en,"As a child, Ali Neuman narrowly escaped being ...",7.492,2013-12-04,6.7,403

In [15]:
# check duplicate movie ids
movies[movies["id"].duplicated(keep=False)].sort_values("title")

Empty DataFrame
Columns: [id, title, genre, original_language, overview, popularity, release_date, vote_average, vote_count]
Index: []

In [19]:
# check if overviews are meaningful
movies["overview_word_count"] = movies["overview"].str.split().str.len()
movies[movies["overview_word_count"] < 10][
    ["title", "overview", "overview_word_count"]
].sort_values("overview_word_count")

,title,overview,overview_word_count
392,Tel chi el telùn,A comedy show.,3
7919,Sconnessi,During a weekend there's no internet.,6
4978,The Seventh Company Outdoors,The third part of Seventh Company adventures.,7
8159,"Grande, grosso e Verdone",A comic movie divided in three episodes.,7
1810,The Seventh Company Has Been Found,The second part of the Seventh Company adventu...,8
1814,Pelé: Birth of a Legend,"The life story of Brazilian football legend, P...",8
8764,Three Steps Over Heaven,A bad boy and a socialite girl hook-up.,8
9135,Tifosi,Four different stories about italian football ...,8
9985,Ma tu di che segno 6?,A few stories about the different Zodiac signs.,8
594,Gone Mom: The Disappearance of Jennifer Dulos,"Jennifer Dulos, the wealthy, Connecticut mothe...",9
3914,Broken,Three suburban English families' lives intertw...,9
5944,Before I Wake,An orphaned child's dreams—and nightmares—mani...,9
7712,Mother's Day,Intersecting stories with different moms colli...,9
8969,Non c'è campo,On a school trip the kids can't use internet.,9
9987,Ducoboo 2: Crazy Vacation,Ducobu goes on holiday in the south of France.,9

In [20]:
movies = movies[movies["overview"].str.lower() != "a comedy show"]

In [21]:
movies[movies["overview"].str.lower() == "a comedy show"]

Empty DataFrame
Columns: [id, title, genre, original_language, overview, popularity, release_date, vote_average, vote_count, overview_word_count]
Index: []

In [22]:
movies

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count,overview_word_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862,69
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731,70
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280,48
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959,29
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811,39
...,...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347,36
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417,18
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332,61
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668,36
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221,41

In [24]:
movies["id"].duplicated().sum()

np.int64(0)

In [27]:
(movies["overview"].str.strip() == "").sum()

np.int64(0)

In [28]:
movies = movies.drop(columns=["overview_word_count"])

In [29]:
movies.to_csv("movies_cleaned_up.csv", index=False)